### PR TITLE
New fields mapped and Clojure 1.5

### PR DESCRIPTION
**Pull request by narkisr**
Thanks you for creating the library iv found it very easy to follow and extend

Iv added couple of fields mappings and moved Clojure version to 1.5.1

Best regards
Ronen

### CODE REVIEW

**Comment by mrowe** [comment]
Hi Ronen,

Thanks for that, the new fields look great.

I'm a little reluctant to require Clojure 1.5 unless absolutely necessary, it just makes life harder for people who are stuck on an old version for some reason. Would `map` work just as well as `mapv` for you there?

**Comment by narkisr** [comment]
I need it to be a vector because I address it using (get-in m [:key ... 0])

Regarding using 1.5.1 its easy to revert to 1.2.1 by replacing it to (into [](map ..)) ill to that ill send you another pull request

**Comment by mrowe** [comment]
I'd really rather keep the API consistent--everything else returns maps or seqs. In general, I feel that libraries like this should use the most abstract data type possible.

And if you do the conversion to a vector in your client code, you can keep using Clojure 1.5 and `mapv`. :-)

**Comment by michaelneale** [comment]
What about tags? can you use tags to delete unneeded servers?

**Comment by narkisr** [comment]
Ok thank you

**Comment by mrowe** [comment]
I've manually pulled these commits into `master` and released `0.2.1`. Thanks again!

**Comment by narkisr** [comment]
Your welcome

**Pull request closed without merging**
